from sqlalchemy import Column, Integer, String, Float, Boolean, BigInteger
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.dialects.postgresql import UUID
import uuid


Base = declarative_base()


class BioTimeQueryDataSet(Base):
    """
    BioTIMEQuery_24_06_2021.csv dataset
    """

    __tablename__ = "bio_time_query_24_06_2021"

    id = Column(Integer, primary_key=True)
    study_id = Column(Integer)
    day = Column(String, nullable=True)
    month = Column(String, nullable=True)
    year = Column(String)
    sample_desc = Column(String)
    plot = Column(String)
    id_species = Column(Integer)
    latitude = Column(Float)  # TODO: geo fields
    longitude = Column(Float)  # TODO: geo fields combined
    abundance = Column(String)
    biomass = Column(String)
    genus = Column(String)
    species = Column(String)
    genus_species = Column(String)


class YourDataTable(Base):
    """
    obis_20230208.csv dataset
    """

    __tablename__ = "obis_20230208"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    dataset_id = Column(String, nullable=True)
    decimallongitude = Column(Float, nullable=True)
    decimallatitude = Column(Float, nullable=True)
    date_start = Column(BigInteger, nullable=True)  # Handling Unix timestamp
    date_mid = Column(BigInteger, nullable=True)
    date_end = Column(BigInteger, nullable=True)
    date_year = Column(Integer, nullable=True)
    scientificname = Column(String, nullable=True)
    originalscientificname = Column(String, nullable=True)
    minimumdepthinmeters = Column(Float, nullable=True)
    maximumdepthinmeters = Column(Float, nullable=True)
    depth = Column(Float, nullable=True)
    coordinateuncertaintyinmeters = Column(Float, nullable=True)
    flags = Column(String, nullable=True)  # TODO: figure out data type
    dropped = Column(Boolean, nullable=True)
    absence = Column(Boolean, nullable=True)
    shoredistance = Column(Float, nullable=True)
    bathymetry = Column(Float, nullable=True)
    sst = Column(Float, nullable=True)
    sss = Column(Float, nullable=True)
    marine = Column(Boolean, nullable=True)
    brackish = Column(Boolean, nullable=True)
    freshwater = Column(Boolean, nullable=True)
    terrestrial = Column(Boolean, nullable=True)
    taxonrank = Column(String, nullable=True)
    aphiaid = Column(Integer, nullable=True)
    redlist_category = Column(String, nullable=True)
    superdomain = Column(String, nullable=True)
    domain = Column(String, nullable=True)
    kingdom = Column(String, nullable=True)
    subkingdom = Column(String, nullable=True)
    infrakingdom = Column(String, nullable=True)
    phylum = Column(String, nullable=True)
    phylum_division = Column(String, nullable=True)
    subphylum_subdivision = Column(String, nullable=True)
    subphylum = Column(String, nullable=True)
    infraphylum = Column(String, nullable=True)
    parvphylum = Column(String, nullable=True)
    gigaclass = Column(String, nullable=True)
    megaclass = Column(String, nullable=True)
    superclass = Column(String, nullable=True)
    class_ = Column(String, nullable=True)
    subclass = Column(String, nullable=True)
    infraclass = Column(String, nullable=True)
    subterclass = Column(String, nullable=True)
    superorder = Column(String, nullable=True)
    order = Column(String, nullable=True)
    suborder = Column(String, nullable=True)
    infraorder = Column(String, nullable=True)
    parvorder = Column(String, nullable=True)
    superfamily = Column(String, nullable=True)
    family = Column(String, nullable=True)
    subfamily = Column(String, nullable=True)
    supertribe = Column(String, nullable=True)
    tribe = Column(String, nullable=True)
    subtribe = Column(String, nullable=True)
    genus = Column(String, nullable=True)
    subgenus = Column(String, nullable=True)
    section = Column(String, nullable=True)
    subsection = Column(String, nullable=True)
    series = Column(String, nullable=True)
    species = Column(String, nullable=True)
    subspecies = Column(String, nullable=True)
    natio = Column(String, nullable=True)
    variety = Column(String, nullable=True)
    subvariety = Column(String, nullable=True)
    forma = Column(String, nullable=True)
    subforma = Column(String, nullable=True)
    type = Column(String, nullable=True)
    modified = Column(String, nullable=True)
    language = Column(String, nullable=True)
    license = Column(String, nullable=True)
    rightsholder = Column(String, nullable=True)
    accessrights = Column(String, nullable=True)
    bibliographiccitation = Column(String, nullable=True)
    references = Column(String, nullable=True)
    institutionid = Column(String, nullable=True)
    collectionid = Column(String, nullable=True)
    datasetid = Column(String, nullable=True)
    institutioncode = Column(String, nullable=True)
    collectioncode = Column(String, nullable=True)
    datasetname = Column(String, nullable=True)
    ownerinstitutioncode = Column(String, nullable=True)
    basisofrecord = Column(String, nullable=True)
    informationwithheld = Column(String, nullable=True)
    datageneralizations = Column(String, nullable=True)
    dynamicproperties = Column(String, nullable=True)
    materialsampleid = Column(String, nullable=True)
    occurrenceid = Column(String, nullable=True)
    catalognumber = Column(String, nullable=True)
    occurrenceremarks = Column(String, nullable=True)
    recordnumber = Column(String, nullable=True)
    recordedby = Column(String, nullable=True)
    recordedbyid = Column(String, nullable=True)
    individualcount = Column(String, nullable=True)
    organismquantity = Column(String, nullable=True)
    organismquantitytype = Column(String, nullable=True)
    sex = Column(String, nullable=True)
    lifestage = Column(String, nullable=True)
    reproductivecondition = Column(String, nullable=True)
    behavior = Column(String, nullable=True)
    establishmentmeans = Column(String, nullable=True)
    occurrencestatus = Column(String, nullable=True)
    preparations = Column(String, nullable=True)
    disposition = Column(String, nullable=True)
    othercatalognumbers = Column(String, nullable=True)
    associatedmedia = Column(String, nullable=True)
    associatedreferences = Column(String, nullable=True)
    associatedsequences = Column(String, nullable=True)
    associatedtaxa = Column(String, nullable=True)
    organismid = Column(String, nullable=True)
    organismname = Column(String, nullable=True)
    organismscope = Column(String, nullable=True)
    associatedoccurrences = Column(String, nullable=True)
    associatedorganisms = Column(String, nullable=True)
    previousidentifications = Column(String, nullable=True)
    organismremarks = Column(String, nullable=True)
    eventid = Column(String, nullable=True)
    parenteventid = Column(String, nullable=True)
    samplingprotocol = Column(String, nullable=True)
    samplesizevalue = Column(String, nullable=True)
    samplesizeunit = Column(String, nullable=True)
    samplingeffort = Column(String, nullable=True)
    eventdate = Column(String, nullable=True)
    eventtime = Column(String, nullable=True)
    startdayofyear = Column(String, nullable=True)
    enddayofyear = Column(String, nullable=True)
    year = Column(String, nullable=True)
    month = Column(String, nullable=True)
    day = Column(String, nullable=True)
    verbatimeventdate = Column(String, nullable=True)
    habitat = Column(String, nullable=True)
    fieldnumber = Column(String, nullable=True)
    fieldnotes = Column(String, nullable=True)
    eventremarks = Column(String, nullable=True)
    locationid = Column(String, nullable=True)
    highergeographyid = Column(String, nullable=True)
    highergeography = Column(String, nullable=True)
    continent = Column(String, nullable=True)
    waterbody = Column(String, nullable=True)
    islandgroup = Column(String, nullable=True)
    island = Column(String, nullable=True)
    country = Column(String, nullable=True)
    countrycode = Column(String, nullable=True)
    stateprovince = Column(String, nullable=True)
    county = Column(String, nullable=True)
    municipality = Column(String, nullable=True)
    locality = Column(String, nullable=True)
    verbatimlocality = Column(String, nullable=True)
    verbatimelevation = Column(String, nullable=True)
    minimumelevationinmeters = Column(String, nullable=True)
    maximumelevationinmeters = Column(String, nullable=True)
    verbatimdepth = Column(String, nullable=True)
    minimumdistanceabovesurfaceinmeters = Column(String, nullable=True)
    maximumdistanceabovesurfaceinmeters = Column(String, nullable=True)
    locationaccordingto = Column(String, nullable=True)
    locationremarks = Column(String, nullable=True)
    verbatimcoordinates = Column(String, nullable=True)
    verbatimlatitude = Column(String, nullable=True)
    verbatimlongitude = Column(String, nullable=True)
    verbatimcoordinatesystem = Column(String, nullable=True)
    verbatimsrs = Column(String, nullable=True)
    geodeticdatum = Column(String, nullable=True)
    coordinateprecision = Column(String, nullable=True)
    pointradiusspatialfit = Column(Float, nullable=True)
    footprintwkt = Column(String, nullable=True)
    footprintsrs = Column(String, nullable=True)
    footprintspatialfit = Column(Float, nullable=True)
    georeferencedby = Column(String, nullable=True)
    georeferenceddate = Column(String, nullable=True)
    georeferenceprotocol = Column(String, nullable=True)
    georeferencesources = Column(String, nullable=True)
    georeferenceverificationstatus = Column(String, nullable=True)
    georeferenceremarks = Column(String, nullable=True)
    geologicalcontextid = Column(String, nullable=True)
    earliesteonorlowesteonothem = Column(String, nullable=True)
    latesteonorhighesteonothem = Column(String, nullable=True)
    earliesteraorlowesterathem = Column(String, nullable=True)
    latesteraorhighesterathem = Column(String, nullable=True)
    earliestperiodorlowestsystem = Column(String, nullable=True)
    latestperiodorhighestsystem = Column(String, nullable=True)
    earliestepochorlowestseries = Column(String, nullable=True)
    latestepochorhighestseries = Column(String, nullable=True)
    earliestageorloweststage = Column(String, nullable=True)
    latestageorhigheststage = Column(String, nullable=True)
    lowestbiostratigraphiczone = Column(String, nullable=True)
    highestbiostratigraphiczone = Column(String, nullable=True)
    lithostratigraphicterms = Column(String, nullable=True)
    group = Column(String, nullable=True)
    formation = Column(String, nullable=True)
    member = Column(String, nullable=True)
    bed = Column(String, nullable=True)
    identificationid = Column(String, nullable=True)
    identifiedby = Column(String, nullable=True)
    identifiedbyid = Column(String, nullable=True)
    dateidentified = Column(String, nullable=True)
    identificationreferences = Column(String, nullable=True)
    identificationremarks = Column(String, nullable=True)
    identificationqualifier = Column(String, nullable=True)
    identificationverificationstatus = Column(String, nullable=True)
    typestatus = Column(String, nullable=True)
    taxonid = Column(String, nullable=True)
    scientificnameid = Column(String, nullable=True)
    acceptednameusageid = Column(String, nullable=True)
    parentnameusageid = Column(String, nullable=True)
    originalnameusageid = Column(String, nullable=True)
    nameaccordingtoid = Column(String, nullable=True)
    namepublishedinid = Column(String, nullable=True)
    taxonconceptid = Column(String, nullable=True)
    acceptednameusage = Column(String, nullable=True)
    parentnameusage = Column(String, nullable=True)
    originalnameusage = Column(String, nullable=True)
    nameaccordingto = Column(String, nullable=True)
    namepublishedin = Column(String, nullable=True)
    namepublishedinyear = Column(Integer, nullable=True)
    higherclassification = Column(String, nullable=True)
    specificepithet = Column(String, nullable=True)
    infraspecificepithet = Column(String, nullable=True)
    verbatimtaxonrank = Column(String, nullable=True)
    scientificnameauthorship = Column(String, nullable=True)
    vernacularname = Column(String, nullable=True)
    nomenclaturalcode = Column(String, nullable=True)
    taxonomicstatus = Column(String, nullable=True)
    nomenclaturalstatus = Column(String, nullable=True)
    taxonremarks = Column(String, nullable=True)
